name: CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master


  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:

  prereqs:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Prepare Host
        run: |
          curl -sLS https://get.arkade.dev | sudo sh
          arkade get kubectl
          sudo mv $HOME/.arkade/bin/kubectl /usr/local/bin

  kubernetes:
    name: Kubernetes
    runs-on: self-hosted
    needs: prereqs
    strategy:
      matrix:
        k8s: [v1.16.15, v1.18.19, v1.19.11, v1.20.7, v1.21.2, v1.22.4, v1.23.3]
    steps:
      - uses: actions/checkout@v1

      - name: Create Kubernetes ${{ matrix.k8s }} cluster
        id: kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: v0.11.1
          image: kindest/node:${{ matrix.k8s }}

      - name: Test crds
        run: |
          echo "waiting for nodes to be ready ..."
          kubectl wait --for=condition=Ready nodes --all --timeout=5m
          kubectl get nodes
          kubectl create -R -f ./crds
